services:
  app:
    image: anishaaaa21/laravel-podcast:V1
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
