services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - postgres
      - mongodb
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: user
      DB_PASSWORD: secret

      PGSQL_DB_CONNECTION: pgsql
      PGSQL_DB_HOST: postgres
      PGSQL_DB_PORT: 5432
      PGSQL_DB_DATABASE: laravel_pg
      PGSQL_DB_USERNAME: pguser
      PGSQL_DB_PASSWORD: secret

      MONGO_DB_CONNECTION: mongodb
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABASE: mongo
      MONGO_DB_USERNAME: mongouser
      MONGO_DB_PASSWORD: secret

  mysql:
    image: mysql:5.7
    ports:

      - 3307:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: laravel_pg
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  pg_data:
  mongo_data:
