name: Laravel CI and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install dependencies
      run: |
        cp .env.example .env
        composer install
        php artisan key:generate

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    - name: Deploy to EC2 via SSH
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/laravelpodcast-app
          git pull origin main
          composer install --no-interaction --prefer-dist
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache