name: Laravel CI/CD with Docker Compose

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t anishaaaa21/laravel-podcast:V1 .
          docker push anishaaaa21/laravel-podcast:V1

  deploy:
    name: Deploy to EC2 using Docker Compose
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Update and install Docker and Docker Compose
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            fi
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Clone or pull latest repo
            if [ -d "laravelpodcast-deploy" ]; then
              cd laravelpodcast-deploy
              git pull
            else
              git clone https://github.com/anishs21/laravelpodcast-deploy.git
              cd laravelpodcast-deploy
            fi

            # Run Docker Compose
            docker compose down || true
            docker compose pull
            docker compose up -d --build
